### ISSUE TITLE
Add ScottFree Z-Machine Interpreter for Z80

### ISSUE THREAD

**Issue by feilipu** [z88dk/z88dk-ext#3]
Would it be possible to add a version of ScottFree for z88dk to this repo, @zx70 ?

Ideally (at least from my perspective) for CP/M with ANSI Terminal graphics code support.

A reference to [Hybernated1](https://8bitgames.itch.io/hibernated1) just popped up, and this request is joining the dots.

```
/*
 *	ScottFree Revision 1.14
 *	Adapted by Stefano Bodrato to run in tiny environments.
 *	
 *	This program is free software; you can redistribute it and/or
 *	modify it under the terms of the GNU General Public License
 *	as published by the Free Software Foundation; either version
 *	2 of the License, or (at your option) any later version.
 *
 *
 *	You must have an ANSI C compiler to build this program.

Examples:
	zcc +zxansi -D__Z88DK__ -lzxmdv -lmalloc -create-app -DDEBUG -zorg=28000 scottzx.c
 */
```

Ref: https://github.com/z88dk/z88dk/issues/750

**Comment by zx70** [comment]
Sure, I picked my old work and I'm checking/ updating it.
It looks like it's not straightforward as I expected to be,  thus I think I'll begin by sharing the actual code to be discussed.

**Comment by zx70** [comment]
Here are the files:
https://github.com/z88dk/z88dk-ext/blob/master/text-games/scottzx.c
https://github.com/z88dk/z88dk-ext/blob/master/text-games/scottzx.h
https://github.com/z88dk/z88dk-ext/blob/master/text-games/adv00

I updated the malloc() part but it looks like a couple of bugs/differences are still in.
I think @suborb can use it to track them down (e.g. the warning regarding the bit shifting on long types).
There must also be an instability possibly due to a memory leak preventing the first input phase to determine the file to be loaded, an hardcoded filename works on CP/M.

As soon as we'll find and fix the big issues I can clean it up furtherly with memory and console optimizations.

**Comment by feilipu** [comment]
Is it a good time to have a look at the current files?

Is there a good reference build to contrast?

**Comment by zx70** [comment]
I never produced a CP/M version before.   The good reference build in the zx Spectrum version is possible in theory,  but it would be too different from the current compiler. 
I confirm it worked on a real zx microdrive  :)
The source code I put in the repository is a valid C program,  it can be built on Windows or Linux too.
The current spectrum build is not good,  though. 
I think you can easily work around most of the bugs by removing the interactive filename (it is rather a number appended to a name radix)  prompt and making it hardcoded or picking it from argv[1].
I don't know whether the bit shifting warning is a problem,  you would hit the bug only on those games dealing with dark  rooms and limited light resources.

**Comment by zx70** [comment]
I see we're both tuning the game :)
I'm now going to merge in an option to insulate the ZX Spectrum filename trick and recover the original command line  options for the OS based versions (CP/M, Windows, Linux, MACOS..).

**Comment by feilipu** [comment]
Just reading and tweaking currently. I've nothing uncommitted, so go for it.

BTW, is adv00 a game file, or a dictionary?

**Comment by zx70** [comment]
it's a game.
The current files permit a valid build in cp/m, the game can be loaded and run.   There's probably still some kind of overflow because the entered text gets sometimes corrupt.

**Comment by suborb** [comment]
It looks like it also works under ticks - I had to remove the heap code and use AMALLOC to do setup the heap properly.

**Comment by feilipu** [comment]
Thinking of doing another option to include a game file within the build, to allow use in simple targets.

Specifically with +rc2014 -subtype=basic to allow people with a minimum MBASIC z80 system to [upload](https://github.com/RC2014Z80/RC2014/tree/master/BASIC-Programs/hexload) and play.

__Edit__ this won't work because the game file is too big to fit in memory in entirety. Doh!

**Comment by zx70** [comment]
Exactly, this game engine uses the old TRS80 file format,  what you'd like to have is a z-machine interpreter working on the newer metacode format (z-code).
When I ported this one my interest was to demonstrate the power of the microdrive file drivers and of z88dk in general (malloc, VT features, etc).

**Comment by zx70** [comment]
btw there are  about 20 game  files  existing in trs80 format, including the free one I've uploaded

**Comment by feilipu** [comment]
Thanks @zx70, much appreciated for adding this.
I'll close this Q issue now. :+1:

**Comment by zx70** [comment]
Look also at dallas.c, I ported it from an ancient game in BASIC (December 1982) for the ZX Spectrum.
It is buggy, I fixed something I probably messed up in the translation but quite a number of bugs existed in the original version too :)
